version: '2.4'
services:

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        depends_on:
            - rsu1
            - obu1
            - obu2
        container_name: "api"
        ports:
            - "8080:8000"
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.254

    frontend:
        build:
            context: ./webapp
            dockerfile: Dockerfile
        container_name: "FrontEnd"
        volumes:
            - './webapp:/app'
            - '/app/node_modules'
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - "3000:3000"
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.253

    rsu1:
        hostname: rsu1
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        container_name: "RSU1"
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true

        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.100
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini

    obu1:
        hostname: obu1
        container_name: "obu1"
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_USE_HARDCODED_GPS=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini

    gen_obu1:
        build:
            context: ./vanetza-master/examples
            dockerfile: obu.Dockerfile
        depends_on:
            - obu1
        container_name: "gen_obu1"
        environment:
            - VANETZA_STATION_ID=2
            - INTENT=[0,1,2,11,12,13]
            - OBU_MQTT_IP=192.168.98.10
            - OBU_MQTT_PORT=1883
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.11


    obu2:
        hostname: obu2
        container_name: "obu2"
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=3
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:03
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_USE_HARDCODED_GPS=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini

    gen_obu2:
        build:
            context: ./vanetza-master/examples
            dockerfile: obu.Dockerfile
        depends_on:
            - obu2
        container_name: "gen_obu2"
        environment:
            - VANETZA_STATION_ID=3
            - INTENT=[3,4,5,6,7,10,13]
            - OBU_MQTT_IP=192.168.98.20
            - OBU_MQTT_PORT=1883
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.21

    obu3:
        hostname: obu3
        container_name: "obu3"
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=4
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:04
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_USE_HARDCODED_GPS=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.30
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini

    gen_obu3:
        build:
            context: ./vanetza-master/examples
            dockerfile: obu.Dockerfile
        depends_on:
            - obu3
        container_name: "gen_obu3"
        environment:
            - VANETZA_STATION_ID=4
            - INTENT=[11,12,1,2]
            - OBU_MQTT_IP=192.168.98.30
            - OBU_MQTT_PORT=1883
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.31

    obu4:
        hostname: obu4
        container_name: "obu4"
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=5
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:05
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_USE_HARDCODED_GPS=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.40
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini

    gen_obu4:
        build:
            context: ./vanetza-master/examples
            dockerfile: obu.Dockerfile
        depends_on:
            - obu4
        container_name: "gen_obu4"
        environment:
            - VANETZA_STATION_ID=5
            - INTENT=[8,9,4,5]
            - OBU_MQTT_IP=192.168.98.40
            - OBU_MQTT_PORT=1883
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.41

    obu5:
        hostname: obu5
        container_name: "obu5"
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=6
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:06
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_USE_HARDCODED_GPS=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.50
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini

    gen_obu5:
        build:
            context: ./vanetza-master/examples
            dockerfile: obu.Dockerfile
        depends_on:
            - obu5
        container_name: "gen_obu5"
        environment:
            - VANETZA_STATION_ID=6
            - INTENT=[10,13,0,3]
            - OBU_MQTT_IP=192.168.98.50
            - OBU_MQTT_PORT=1883
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.51

    obu6:
        hostname: obu6
        container_name: "obu6"
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=7
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:06
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_USE_HARDCODED_GPS=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.60
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini

    gen_obu6:
        build:
            context: ./vanetza-master/examples
            dockerfile: obu.Dockerfile
        depends_on:
            - obu6
        container_name: "gen_obu6"
        environment:
            - VANETZA_STATION_ID=7
            - INTENT=[6,7,10,3]
            - OBU_MQTT_IP=192.168.98.60
            - OBU_MQTT_PORT=1883
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.61

    obu7:
        hostname: obu7
        container_name: "obu7"
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=8
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:07
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_USE_HARDCODED_GPS=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.70
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini

    gen_obu7:
        build:
            context: ./vanetza-master/examples
            dockerfile: obu.Dockerfile
        depends_on:
            - obu7
        container_name: "gen_obu7"
        environment:
            - VANETZA_STATION_ID=8
            - INTENT=[11,12,3,8]
            - OBU_MQTT_IP=192.168.98.70
            - OBU_MQTT_PORT=1883
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.71

    obu8:
        hostname: obu8
        container_name: "obu8"
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=9
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:08
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_USE_HARDCODED_GPS=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.80
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini

    gen_obu8:
        build:
            context: ./vanetza-master/examples
            dockerfile: obu.Dockerfile
        depends_on:
            - obu8
        container_name: "gen_obu8"
        environment:
            - VANETZA_STATION_ID=9
            - INTENT=[4,10,13,0,1,3]
            - OBU_MQTT_IP=192.168.98.80
            - OBU_MQTT_PORT=1883
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.81

    gen_rsu1:
        build:
            context: ./vanetza-master/examples
            dockerfile: rsu.Dockerfile
        depends_on:
            - rsu1
        container_name: "gen_rsu1"
        environment:
            - RSU_MQTT_IP=192.168.98.100
            - RSU_MQTT_PORT=1883
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.101

    rsu2:
        hostname: rsu2
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        container_name: "RSU2"
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=10
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:10
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true

        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.110
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini



networks:
  vanetzalan0:
    external: true
