version: '2.4'
services:
#    influxdb:
#        image: influxdb:latest
#        restart: unless-stopped
#        environment:
#          - INFLUXDB_USER=influxdbuser
#          - INFLUXDB_PASSWORD=influxdbpassword
#          - INFLUXDB_DATABASE=mqtt_data
#        volumes:
#          - influxdb-data:/var/lib/influxdb2
#        ports:
#          - "8086:8086"
#        networks:
#            vanetzalan0:
#                ipv4_address: 192.168.98.254
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        depends_on:
            - rsu
            - obu
        container_name: "api"
        ports:
            - "8080:8000"
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.254

    frontend:
        build:
            context: ./webapp
            dockerfile: Dockerfile
        container_name: "FrontEnd"
        ports:
            - "80:3000"
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.253

    rsu:
        hostname: rsu
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_USE_HARDCODED_GPS=true
            - VANETZA_LATITUDE=40.642678
            - VANETZA_LONGITUDE=-8.648147
            - VANETZA_CAM_PERIODICITY=1000
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini


    obu:
        hostname: obu
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_USE_HARDCODED_GPS=true
            - VANETZA_LATITUDE=40.641754
            - VANETZA_LONGITUDE=-8.652605
            - VANETZA_CAM_PERIODICITY=1000
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
        volumes:
            - ./vanetza-master/tools/socktap/config.ini:/config.ini


networks:
  vanetzalan0:
    external: true

# volumes:
#   influxdb-data:volumes:
#   influxdb-data: